---
- name: build app container
  shell: "cd {{cf_base_dir}}/meteor/bundle; docker-compose build --no-cache meteor_server"

- name: run docker compose
  shell: "cd {{cf_base_dir}}/meteor/bundle; docker-compose up -d"