---
- name: check nginx is running
  docker_container:
    name: nginx_proxy
    state: started
    image: jwilder/nginx-proxy

- name: check mongo_db is running
  docker_container:
    name: mongodb_server
    state: started
    image: mongo:3.2.6

- name: check meteor_server is running
  docker_container:
    name: meteor_server
    state: started
    image: bundle_meteor_server
