---
- cron:
    name: "mongodb backup every half hour"
    minute: "0,30"
    job: "/usr/bin/docker exec -i mongodb_server /bin/sh /data/do_backup.sh >> {{cf_base_dir}}/../crondebug.txt 2>&1"

- cron:
    name: "delete backups that are older than 7 days"
    minute: "45"
    hour: "2"
    job: 'find /root/cfcalendar/mongo/data/cfcalendar-admin-db-backup -mtime +7 -exec rm -rf {} \;'

- cron:
    name: "send daily backup mail"
    minute: "45"
    hour: "2"
    job: "sh /root/cfcalendar/mongo/data/daily_backup_mail.sh"


# 0,30 * * * * /usr/bin/docker exec -i mongodb_server /bin/sh /data/do_backup.sh >> /root/crondebug.txt 2>&1
# 45 2 * * * find /root/cfcalendar/mongo/data/cfcalendar-admin-db-backup -mtime +7 -exec rm -rf {} \;
# 05 3 * * * sh /root/cfcalendar/mongo/data/daily_backup_mail.sh
# # 45 3 * * * find /root/cfcalendar/*.tar.gz* -mtime +30 -exec rm -rf {} \;